sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - '2.0'
  - '2.1'
  - '2.2'
  - jruby-18mode
  - jruby-19mode
  - ree
script:
  - make test
  - bundle exec image_optim --info
  - bundle exec rspec
before_install:
  if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install imagemagick; fi
matrix:
  fast_finish: true
  include:
    - os: osx
      rvm: default
    - env: RUBOCOP=✓
      rvm: '2'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2'
      script: bundle exec travis_check_rubies
